### ISSUE TITLE
Update PFSense

### ISSUE THREAD

**Issue by usscarter** [ndejong/pfsense_fauxapi#28]
Hello,

Is there any intentions on adding the ability to update the PFsense server via this API?

We have a few hundred PFsense's deployed throughout our environments, and let me tell you. That is one of the largest saviors of time we could possibly get.

**Comment by ndejong** [comment]
At the last revision I made a conscious decision to focus FauxAPI on
features that manage and manipulate the configuration only - there are some
features that are beyond that scope that were added early on and they will
remain but keeping the scope of FauxAPI is important i believe.

That said, what you are talking about would indeed be a useful toolchain -
I’m sure something appropriate could be cooked up to suit your use case -
contact me privately via email to figure something out.


On 14 Aug 2018, at 20:21, Stephen Carter <notifications@github.com> wrote:

Hello,

Is there any intentions on adding the ability to update the PFsense server
via this API?

We have a few hundred PFsense's deployed throughout our environments, and
let me tell you. That is one of the largest saviors of time we could
possibly get.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ndejong/pfsense_fauxapi/issues/28>, or mute the thread
