### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by jamesspi** [ndejong/pfsense_fauxapi#3]
Hi,

Firstly, I think this is great, thanks for the initiative!

I was wondering - could you confirm if for config changes, I would need to supply the entire modified config in the payload? Lets say I want to modify my aliases, would I need to make the modification to the json file in its entirety, and then submit it?

Thanks!
James

**Comment by ndejong** [comment]
Yes, you need to provide the full modified payload, this is because it's not a "real" API that hooks into each respective control-layer of the pfSense web application, it is indeed a fauxAPI that works as a configuration manipulation interface to the pfSense config.xml file.  

If you take a closer look at the Python client-lib it does provide a way to submit configuration sections, however you notice that it simply does a config_get to obtain the existing config file first and then overwrites with the user supplied (new) configuration section.

There is no escaping this, fauxAPI is what it is because pfSense does not have a well defined or standardised application control layer to interface with - to this end, the OPNSense fork appears to have adopted a well defined application architecture with a control layer API and will likely become the preferred dev-ops solution that fauxAPI set out to gap-fill for.
