### ISSUE TITLE
authentication problem

### ISSUE THREAD

**Issue by sangeetha-nair** [ndejong/pfsense_fauxapi#4]
Hi, 
I am entirely new to "pfsense" and "fauxApi".
I have pfsense installed in a VM and i am trying to get its config details using  RESTClient.
I always get a "Unauthorized"error whenever i try to do "config_get" or any other operation. 
I am pretty sure the issue is with the "fauxapi_auth" that i provide in the header but the issue is i don't understand how to solve it. I did try giving certain values in the credentials.ini file but still the same error.
It will be very helpful if anyone could provide me a solution.

**Comment by ndejong** [comment]
Hi 

Setting the API credentials is a bit pedantic, in an effort to prevent poor choices.

You'll likely find the issue quickly if you simply add a GET input parameter in the form __debug=true to your request since as this causes the response data to include debugging log information.

Failing this, I'd recommend the following, re-read of the api-authentication documentation here first:-
https://github.com/ndejong/pfsense_fauxapi#api-authentication

Then go and take a closer look at the credentials file here:-
/etc/fauxapi/credentials.ini

Take careful notice of the 4x rules, namely:-
 - <apikey_value> and <apisecret_value> may have alphanumeric chars ONLY!
 - <apikey_value> MUST start with the prefix PFFA (pfSense Faux API)
 - <apikey_value> MUST be >= 12 chars AND <= 40 chars in total length
 - <apisecret_value> MUST be >= 40 chars AND <= 128 chars in length

Also note that you can't use one of the example key values, these are prevented for use by the API.

N
