### ISSUE TITLE
Instruction Update

### ISSUE THREAD

**Issue by Strider11** [ndejong/pfsense_fauxapi#78]
I spent multiple days trying to figure out why I couldn't get this working.  Only to find out that I had PFSense setup as HTTP access, when FauxAPI requires HTTPS.  Could you add a note to the installation instructions to prevent some other n00b from making my same mistake?

**Comment by ndejong** [comment]
Hi - I note that you self-closed this however I'm interested in understanding if there is something more that should be added to the documentation.

There is a place in [fauxApiPfsenseInterface::system_load_config()](https://github.com/ndejong/pfsense_fauxapi/blob/14e6cc0f630f1a8d613f681f73349874a649305a/pfSense-pkg-FauxAPI/files/etc/inc/fauxapi/fauxapi_pfsense_interface.inc#L400) where FauxAPI does make a localhost call back to itself in order to cause pfSense to regenerate a cache.

I'm wondering if there is some kind of issue with the less-than-ideal `exec()` usage here.

Interested in how you solved this in the end.

**Comment by Strider11** [comment]
Hi, thanks for the concern!
I was really only interested in getting the data about my router into Home Assistant and was using this additional code to do so.  https://github.com/JOHLC/pfSense-FauxAPI-ha 
I believe that was actually where the HTTPS issue came into play, which was why I closed this issue right away.  Either way, as soon as I set my Pfsense install to use HTTPS instead of HTTP, everything connected and worked great for my needs.  

Thank you for all your work!
